/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bizmatech.bizmadtr;


import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author Danielle
 */
public class register extends javax.swing.JFrame {

    DBController dbController;
    /**
     * Creates new form product
     */
    public register() {
        initComponents();
        dbController = new DBController();
    }
    
    private void customInitComponents() {
        URL resource = getClass().getResource("/bizmatech/bizmadtr/REG_BACKGROUND.png");
        if (resource != null) {
            jLabel1.setIcon(new javax.swing.ImageIcon(resource));
        } else {
            System.err.println("Resource not found: /bizmatech/bizmadtr/REG_BACKGROUND.png");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcnumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtidno = new javax.swing.JTextField();
        btnregister = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        hyperlink = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        txtname.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 290, -1));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, -1, -1));

        txtlname.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        getContentPane().add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 290, -1));

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel4.setText("Email Address:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        txtemail.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 410, -1));

        jLabel5.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel5.setText("Contact No. :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        txtcnumber.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        getContentPane().add(txtcnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 410, -1));

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel6.setText("ID No. :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, -1, -1));

        txtidno.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        getContentPane().add(txtidno, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 410, -1));

        btnregister.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        btnregister.setText("Sign Up");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("Already have an account?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, -1, -1));

        hyperlink.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        hyperlink.setForeground(new java.awt.Color(0, 0, 255));
        hyperlink.setText("Proceed Here.");
        hyperlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hyperlinkMouseClicked(evt);
            }
        });
        getContentPane().add(hyperlink, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bizmatech/bizmadtr/REGISTRATION LOGO.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 370, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bizmatech/bizmadtr/REG_BACKGROUND.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hyperlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hyperlinkMouseClicked
        // TODO add your handling code here:
        landingpage lpage = new landingpage();
        lpage.setVisible(true);
        lpage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_hyperlinkMouseClicked

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
        String name = txtname.getText();
        String lastname = txtlname.getText();
        String email = txtemail.getText();
        String contactno = txtcnumber.getText();
        String idNumber = txtidno.getText(); // Get the ID number 

        if (name.isEmpty() || lastname.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please fill in all fields.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean register = dbController.register(name, lastname, email, contactno, idNumber);

        if (register) {
            JOptionPane.showMessageDialog(this,
                "Added successfully!", "Success",
                JOptionPane.INFORMATION_MESSAGE);
            dispose();
            landingpage lpage = new landingpage();
            lpage.setVisible(true);
            lpage.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this,
                "Error",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnregisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnregister;
    private javax.swing.JLabel hyperlink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcnumber;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtidno;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
